name: HT-Homes
version: 4.0.0
main: com.hthomes.HTHomes
api-version: 1.20
author: mustafa8907
description: A professional GUI-based home management system with Geyser support.

commands:
  home:
    description: Open the home list menu.
    usage: /home
    aliases: [homes]
    permission: hthomes.use
  sethome:
    description: Create a new home.
    usage: /sethome <name>
    permission: hthomes.use

permissions:
  hthomes.use:
    description: Allows players to use the home system.
    default: true
  hthomes.admin:
    description: Allows admin operations.
    default: op
  hthomes.limit.default:
    description: Default home limit.
    default: true
