name: HT-Homes
version: 5.1.0
main: com.hthomes.HTHomes
api-version: 1.20
author: mustata8907
website: https://github.com/mustafa8907-png/HT-Homes-plus
description: Ücretsiz ve gelişmiş ev yönetim eklentisi.

commands:
  home:
    description: Ana ev menüsünü açar.
    aliases: [homes, hthomes, ev]
    permission: hthomes.user.home
  sethome:
    description: Yeni bir ev noktası oluşturur.
    aliases: [evayarla, evçek]
    permission: hthomes.user.sethome
  delhome:
    description: Mevcut bir evi siler.
    aliases: [evsil]
    permission: hthomes.user.delhome

permissions:
  hthomes.user.*:
    description: Tüm kullanıcı yetkilerini verir.
    children:
      hthomes.user.home: true
      hthomes.user.sethome: true
      hthomes.user.delhome: true
  hthomes.user.home:
    description: Ev menüsünü açma yetkisi.
    default: true
  hthomes.user.sethome:
    description: Ev kurma yetkisi.
    default: true
  hthomes.user.delhome:
    description: Ev silme yetkisi.
    default: true
  hthomes.admin:
    description: Admin yetkileri (İleride eklenecek reload vb. için).
    default: op
